spring.application.name=Biblioteca

spring.datasource.url=jdbc:oracle:thin:@//192.168.0.200:1522/UNIFIL
spring.datasource.username=unifil
spring.datasource.password=unifil
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=create
jwt.secret="rv"i'#Y.|~DcsW+4T^EDkOxWMO\I2)t5fa9zizd#Qr|_&~WV#-.FU0V8nIKs[9Z($dV*w}J'b-rU=V8~YY\|IE8h\5`3gOD1@F'HD+CacWnfuTUu=gxrw^kJ[B(\=p:%O`JP^gjmk[7#^M?om&'|\0/0)99W<kZOHA<HBHAMMXZAk`?Y^,RUyLoaTniDjz&>-<xhk9X<Sl=_~%9*BCYTf{7U%[0p0/2~=^N{y=GOv_x41@(megW>;-WD$Wh2MbmFCptd/Xl\"8>44wmB3>*bXGs!`/&7i6qdLzamjANRH8iSQsz6hPWnlJE)~*CUKM7Ow`o'B^t9/KOS6:#XX(_4SVi0QrO$lpv/=\-atGzR?H'eae|a}{|x6<u5MrJx90"Om"5NS?)W!%/B.pi=u70}y&b2i{^;rM}rL&POd`uG)XM*K4KHCo`Nn?,Ee:{G#-"v9/Nkn>}teA51zNdPPw`&_.exEkWyg4gT2H!>}k^{*{lcNJ7"%aY